### PR TITLE
cope with su-exec breaking change

### LINKED ISSUE #3756: Unable to start docker container with v3.1.0: "This account is not available"
**Describe the bug**
I am unable to start the docker container with the latest release v3.1.0

**To Reproduce**
0. Using a minimal compose
```yaml
services:
  gerbera:
    image: gerbera/gerbera:latest # With SSDP listener fix
    container_name: gerbera
    restart: unless-stopped
    network_mode: host
```
1. Start the container
```
docker compose up
```
2. Fail
```
$ docker compose up 
Attaching to gerbera
gerbera  | Root DEF
gerbera  | This account is not available
```

**Expected behavior**
The container to start like normal

**Server (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Gerbera Version: v3.1.0
 - Versions of libraries: N/A
 - Source: Docker

### PR DESCRIPTION
**Pull request by cmigliorini**
Should fix #3756 

Works fine with this compose file (fails if `user:` is missing). 
```
services:
  gerbera:
    image: gerbera-mig
    container_name: gerbera
    network_mode: host
    user: gerbera
    volumes:
      - ./gerbera-config-3:/var/run/gerbera
      - /data/multimedia/sea750:/mnt/content:ro

volumes:
  gerbera-config:
    external: false
```

Now all files, including the database, are properly stored in `./gerbera-config-3`.

Other notes:
- image user ID (1042 default) needs to have read access to files on host -- I `chown`ed them, but there might be a better option
- for some reason, log says `gerbera  | 2026-01-18 10:07:09   info: Loading configuration from: /run/gerbera/config.xml`. I was expecting `/var/run/...`

### CODE REVIEW

File: scripts/docker/docker-entrypoint.sh
Comment (cmigliorini) [inline scripts/docker/docker-entrypoint.sh]: Note: line 104 will probably never work as long as user is created with `-s /sbin/nologin` -- see `Dockerfile*`

```
        exec su - $IMAGE_USER -c "/var/run/gerbera/run.sh"
```

File: scripts/docker/docker-entrypoint.sh [hunk 1]
```diff
@@ -95,7 +95,7 @@ fi
 if [[ "$3" =~ "^gerbera " || "$1" == "gerbera" ]]; then
   if [ "$(id -u)" -eq '0' ]; then
     echo "Root DEF"
-    if ! (command su-exec 2>&1) > /dev/null
+    if ! (command su-exec ${IMAGE_USER} /bin/true 2>&1) > /dev/null
```
Comment (KarlStraussberger) [inline scripts/docker/docker-entrypoint.sh]: It has to be `$IMAGE_USER` to be replaced by `gerbera` during image build

**Review by KarlStraussberger — CHANGES_REQUESTED** [review]

**Comment by KarlStraussberger** [comment]
Thank you for investigating the issue.

**Comment by KarlStraussberger** [comment]
this is the reason

https://github.com/ncopa/su-exec/commit/122f0ac51854236c3588a9ccb0eaa120a38cc05d

**Review by KarlStraussberger — APPROVED** [review]
