### PR TITLE
Don't erase from empty vector

### LINKED ISSUE #1969: Master v1.9.1-138-g744621f7 is buggy
It look like it starts up fine, no error when I check the status via `sudo systemctl status gerbera.service` but browsing some of the local web pages doesn't work, I see an `invalid session-id` error at the bottom of the page. Also, when I try to browse a list of movies on my LG OLED tv it says that the server has disconnected.
Playing audio on my speaker with chromecast, via the Hi-Fi Cast app, works.

Gerbera is running in a Proxmox 7 linux-container.

### PR DESCRIPTION
**Pull request by KarlStraussberger**
fixes #1969

### CODE REVIEW

File: src/content/content_manager.cc [hunk 1]
```diff
@@ -1151,7 +1151,9 @@ std::pair<int, bool> ContentManager::addContainerChain(const std::string& chain,
 
     constexpr auto unwanted = std::array { M_DESCRIPTION, M_TITLE, M_TRACKNUMBER, M_ARTIST }; // not wanted for container!
     for (auto&& unw : unwanted) {
-        lastMetadata.erase(std::remove_if(lastMetadata.begin(), lastMetadata.end(), [=](auto&& m) { return m.first == MetadataHandler::getMetaFieldName(unw); }));
+        auto unwIt = std::remove_if(lastMetadata.begin(), lastMetadata.end(), [=](auto&& m) { return m.first == MetadataHandler::getMetaFieldName(unw); });
```
Comment (neheb) [inline src/content/content_manager.cc:1154]: looks like wrong erase usage. iterator parameter is missing.

Comment (KarlStraussberger) [reply src/content/content_manager.cc:1154]:
```
std::vector<T,Allocator>::erase

iterator erase( iterator pos );
```

Looks fine to me

**Comment by KarlStraussberger** [comment]
fixes #1976
