### PR TITLE
Fix sorting by composed keys

### LINKED ISSUE #2479: UPnP sort by track number not working
(Related to https://github.com/gerbera/gerbera/discussions/2475)

I'm using Yamaha MusicCast as my AV client, and I find that tracks are not listed in track number order in the MusicCast app when browsing the Gerbera server. Looking into the debugging, it appears that the sort criteria requested by the client are not being honoured.

The tracks are showing in the correct order in the Gerbera web interface, and clients that sort the tracks themselves (like Bubble UPNP) display them correctly. MusicCast shows the tracks in the right order when I use a different server, like Synology Media Server or Airsonic.

I've attached the debug output from Gerbera. You can see that the request is

```
2022-03-09 00:03:14.383  debug: [upnp_cds.cc:73] doBrowse(): Browse received parameters: ObjectID [784] BrowseFlag [BrowseDirectChildren] StartingIndex [0] RequestedCount [8] SortCriteria [+upnp:originalTrackNumber,+dc:title]
```
``
but the resulting tracks are in alphabetical order not track number order:

```
  <dc:title>Always</dc:title>
  <upnp:originalTrackNumber>6</upnp:originalTrackNumber>
  <dc:title>Blue Monk</dc:title>
  <upnp:originalTrackNumber>5</upnp:originalTrackNumber>
  <dc:title>Desafinado</dc:title>
  <upnp:originalTrackNumber>4</upnp:originalTrackNumber>
  <dc:title>I Want to be Happy</dc:title>
  <upnp:originalTrackNumber>7</upnp:originalTrackNumber>
  <dc:title>Just in Time</dc:title>
  <upnp:originalTrackNumber>2</upnp:originalTrackNumber>
  <dc:title>Say it Isn't So</dc:title>
  <upnp:originalTrackNumber>3</upnp:originalTrackNumber>
  <dc:title>Smiles</dc:title>
  <upnp:originalTrackNumber>1</upnp:originalTrackNumber>
```

[sort.log](https://github.com/gerbera/gerbera/files/8210601/sort.log)

### PR DESCRIPTION
**Pull request by KarlStraussberger**
closes #2479

### CODE REVIEW

File: test/core/test_searchhandler.cc [hunk 1]
```diff
@@ -56,6 +57,7 @@ const std::map<TestCol, std::pair<std::string, std::string>> testColMap = {
     { TestCol::Id, { "t", "id" } },
     { TestCol::ItemId, { "t", "item_id" } },
     { TestCol::PropertyName, { "t", "property_name" } },
+    { TestCol::PropertyName2, { "t", "property_name2" } },
```
Comment (whyman) [inline test/core/test_searchhandler.cc:60]: Shouldnt this be `TestCol::PropertyName` again?

Comment (KarlStraussberger) [reply test/core/test_searchhandler.cc:60]: I simulated `part_number` and `track_number`
